spring:
  profiles:
    active: test

---
spring:
  profiles: test
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: SA
    password:
    driverClassName: org.h2.Driver
#    schema: classpath:schema-h2.sql

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/triple?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
